version: '3.1'
services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    environment:
      ZOO_MAX_CLIENT_CNXNS: 0
    ports:
      - "2181:2181"
  kafka:
    image: ${KAFKA_IMAGE}
    ports:
      - "9092:9092"
    environment:
      # Your computer's IP here.  Run `ifconfig`, then check the `inet` value of `en0`
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.12
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "deck:1:1,top:1:1,bottom:1:1,shuffled:1:1,output:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
